services:
  - type: web
    name: followers-on-door
    env: php
    plan: free
    buildCommand: "composer install --no-dev"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    phpVersion: 8.2
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
